### ISSUE TITLE
Where a are preferences stored?

### ISSUE THREAD

**Issue by starnutoditopo** [sandreas/Avalonia.Preferences#3]
I'm running an Avalonia Desktop application inside a Unix Docker container hosted on Windows. I'd like to persist the user preferences across container runs. To accomplish this, I should be able to save them on a volume. If the preferences are saved on file, a simple way to do this is by mapping (binding) a docker volume on an host's path. So... where are the preferences saved?

**Comment by sandreas** [comment]
Internally it uses the [`IsolatedStorage`](https://stackoverflow.com/questions/275536/where-is-net-isolated-storage-stored) API

**Comment by starnutoditopo** [comment]
Yep. On Windows, preferences are saved _somewhere_ under `%localappdata%\IsolatedStorage`; in Linux it is under `~/.local/share/IsolatedStorage`
